name: ci-golang-workflow
on: 
    pull_request:
        branches:
            - develop
    push:
        branches:
          - develop
jobs:
    # Strategy Matrix Example
    # check-application:
    #     runs-on: ubuntu-latest
    #     strategy:
    #         matrix:
    #             go: ['1.14', '1.15']
    #     steps:
    #         - uses: actions/checkout@v2
    #         - uses: actions/setup-go@v2
    #           with:
    #             go-version: ${{matrix.go}}
    #         - run: cd gomath && go run math.go
    #         - run: cd gomath && go test
    check-application:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2
              with:
                go-version: 1.15
            - run: cd gomath && go run math.go
            - run: cd gomath && go test -coverprofile=coverage.out

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name: Set up QEMU
              if: success() && github.ref == 'refs/heads/develop'
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              if: success() && github.ref == 'refs/heads/develop'
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              if: success() && github.ref == 'refs/heads/develop'
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build
              if: success() && github.ref == 'refs/heads/develop'
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                context: ./gomath
                file: ./gomath/Dockerfile
                push: true
                tags: talessatiro/gomath:latest